package com.exp.uss.model

import com.amazonaws.services.dynamodbv2.datamodeling.*
import java.io.Serializable
import java.util.*


/**
 * User: taweechaimaklay
 * Date: 28/12/2019 AD
 * Time: 11:08
 */
@DynamoDBTable(tableName = "user_table")
class UserDynamo : Serializable{

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private var uuid: String? = null

    open fun getUuid(): String? {
        return uuid
    }

    fun setUuid(uuid: String) {
        this.uuid = uuid
    }
    @DynamoDBAttribute
    private var username: String? = null

    @DynamoDBAttribute
    private var email: String? = null

    @DynamoDBAttribute
    private var password: String? = null

    @DynamoDBAttribute
     var phoneNumber: String? = ""

    @DynamoDBTypeConvertedEnum
    @DynamoDBAttribute
    private var roles: Set<Role>? = null

    fun getUsername(): String? {
        return username
    }

    fun setUsername(username: String?) {
        this.username = username
    }

    fun getEmail(): String? {
        return email
    }

    fun setEmail(email: String?) {
        this.email = email
    }

    fun getPassword(): String? {
        return password
    }

    fun setPassword(password: String?) {
        this.password = password
    }

    fun setRoles(roles: Set<Role>) {
        print("User Created Enum ${roles}")
        this.roles = roles
    }

    fun getRoles(): Set<Role>? {
        print("this role ${this.roles}")
        return this.roles
    }


}